# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-deployment
  namespace: backend
  labels:
    app: rag-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      serviceAccountName: rag-service-account
      containers:
      - name: rag-api
        image: 687436499847.dkr.ecr.ap-northeast-2.amazonaws.com/backend/rag-service:d513d8d4a9695461ee070376bf789f026780423b
        imagePullPolicy: Always
        ports:
        - containerPort: 5201 
        env:
        - name: AWS_REGION
          value: ap-northeast-2